# Generated by Django 4.1.1 on 2022-11-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=333, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "Oliy Ta'lim Muassasasi ",
                'verbose_name_plural': "3. Oliy Ta'lim Muassasalari",
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('fish', models.CharField(max_length=111, verbose_name='Familya Ism Sharifi')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Telfon raqami')),
                ('payment', models.IntegerField(verbose_name='Homiylik summasi')),
                ('juridical', models.BooleanField(default=False, verbose_name='Yuridik')),
                ('organization', models.CharField(blank=True, max_length=333, verbose_name='Tashkilot nomi')),
                ('spent_amount', models.IntegerField(blank=True, default=0, verbose_name='Sarflangan summasi')),
                ('status', models.CharField(choices=[('NEW', 'new'), ('MODERATION', 'moderation'), ('CONFIRMED', 'confirmed'), ('CANCELED', 'canceled')], default='NEW', max_length=33, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Homiy ',
                'verbose_name_plural': '1. Homiylar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('fish', models.CharField(max_length=111, verbose_name='Familya Ism Sharifi')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Telefon raqami')),
                ('student_type', models.CharField(choices=[('BACHELOR', 'bachelor'), ('MASTER', 'master'), ('PhD', 'phd')], default='BACHELOR', max_length=10, verbose_name='Talaba turi')),
                ('contract_amount', models.IntegerField(verbose_name='Kontrakt summasi')),
                ('allocated_amount', models.IntegerField(blank=True, default=0, verbose_name='Ajratilgan summasi')),
                ('otm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.otm', verbose_name="Oliy Ta'lim Muassasasi")),
            ],
            options={
                'verbose_name': 'Talaba ',
                'verbose_name_plural': '2. Talabalar',
            },
        ),
        migrations.CreateModel(
            name='SponsorPayForStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sponsor', verbose_name='Homiy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Homiy summasi talaba uchun ',
                'verbose_name_plural': '4. Homiylar summasi talabalar uchun',
            },
        ),
    ]
