# Generated by Django 4.1 on 2022-09-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=333)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=111)),
                ('phone_number', models.CharField(max_length=17)),
                ('payment', models.IntegerField()),
                ('juridical', models.BooleanField(default=False)),
                ('organization', models.CharField(blank=True, max_length=333)),
                ('spent_amount', models.IntegerField(blank=True, default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('MODERATION', 'moderation'), ('CONFIRMED', 'confirmed'), ('CANCELED', 'canceled')], default='NEW', max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=111)),
                ('phone_number', models.CharField(max_length=17)),
                ('student_type', models.CharField(choices=[('BACHELOR', 'bachelor'), ('MASTER', 'master'), ('PhD', 'phd')], default='BACHELOR', max_length=10)),
                ('contract_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('allocated_amount', models.IntegerField(blank=True, default=0)),
                ('ihe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ihe')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorPayForStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
