# Generated by Django 4.1 on 2022-08-26 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=333)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=111)),
                ('phone_number', models.CharField(max_length=17)),
                ('payment', models.IntegerField()),
                ('juridical', models.BooleanField(default=False)),
                ('organization', models.CharField(blank=True, max_length=333)),
                ('spent_amount', models.IntegerField(blank=True, default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ('Moderatsiyada', 'Moderatsiyada'), ('Tastiqlangan', 'Tastiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=111)),
                ('phone_number', models.CharField(max_length=17)),
                ('student_type', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magister'), ('Doktorant', 'Doktorant')], default='Bakalavr', max_length=10)),
                ('contract_amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('allocated_amount', models.IntegerField(blank=True, default=0)),
                ('otm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.otm')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorPayForStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
