# Generated by Django 4.1.1 on 2022-11-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='spent_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sarflangan summasi'),
        ),
    ]
