# Generated by Django 4.1 on 2022-08-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='status',
            new_name='statuss',
        ),
    ]
