# Generated by Django 4.1.1 on 2022-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sponsor_spent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otm',
            name='name',
            field=models.CharField(max_length=333, verbose_name='OTM nomi'),
        ),
    ]
